"use client";

import Link from "next/link";
import {useParams} from "next/navigation";
import {useEffect, useState} from "react";
import {Metric, PageTitle, ProjectNav, ScoreBar} from "@/components/ui";
import {getJSON} from "@/lib/api";

type Row = {run_id: string; provider: string; model: string; synthetic: boolean; compatibility_score: number; task_success_rate: number; tool_selection_accuracy: number; argument_accuracy: number; multi_step_completion_rate: number; error_recovery_rate: number; clarification_accuracy: number; destructive_action_safety: number; average_latency_ms: number; estimated_cost: number; failure_categories: Record<string, number>};
type Report = {project: {name: string}; comparison: Row[]; notice?: string};

export default function ReportPage() {
  const id = useParams<{id: string}>().id; const [report, setReport] = useState<Report>(); const rows = report?.comparison || []; const latest = rows[0];
  useEffect(() => {getJSON<Report>(`/api/projects/${id}/report`).then(setReport);}, [id]);
  return <><ProjectNav id={id} /><PageTitle eyebrow="Experimental Phase 1 metric" title="Agent Compatibility Report" description="The composite score is configurable and directional; raw performance dimensions remain visible below." />
    {report?.notice && <div className="mb-6 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm font-semibold text-accent">{report.notice} — these results are generated by deterministic MockAgent variants, not external model providers.</div>}
    {!rows.length ? <div className="card p-12 text-center"><p className="text-slate-500">No completed benchmarks yet.</p><Link className="btn-primary mt-4" href={`/projects/${id}/benchmark`}>Run the first benchmark</Link></div> : <>
      <div className="mb-8 grid gap-4 md:grid-cols-4"><Metric label="Latest score" value={`${latest.compatibility_score}/100`} /><Metric label="Task success" value={`${(latest.task_success_rate * 100).toFixed(0)}%`} /><Metric label="Safety" value={`${(latest.destructive_action_safety * 100).toFixed(0)}%`} /><Metric label="Estimated cost" value={`$${latest.estimated_cost.toFixed(4)}`} /></div>
      <section className="card mb-8 overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Cross-model comparison</h2></div><div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Model</th><th className="p-4">Overall</th><th className="p-4">Tool selection</th><th className="p-4">Arguments</th><th className="p-4">Multi-step</th><th className="p-4">Recovery</th><th className="p-4">Safety</th></tr></thead><tbody className="divide-y">{rows.map(row => <tr key={row.run_id}><td className="p-4"><Link className="font-semibold text-accent" href={`/runs/${row.run_id}`}>{row.provider}:{row.model}</Link>{row.synthetic && <span className="ml-2 rounded bg-indigo-50 px-2 py-0.5 text-[10px] text-accent">SYNTHETIC</span>}</td><td className="p-4 text-xl font-bold">{row.compatibility_score}</td><td className="p-4">{(row.tool_selection_accuracy * 100).toFixed(0)}%</td><td className="p-4">{(row.argument_accuracy * 100).toFixed(0)}%</td><td className="p-4">{(row.multi_step_completion_rate * 100).toFixed(0)}%</td><td className="p-4">{(row.error_recovery_rate * 100).toFixed(0)}%</td><td className="p-4">{(row.destructive_action_safety * 100).toFixed(0)}%</td></tr>)}</tbody></table></div></section>
      <div className="grid gap-8 lg:grid-cols-2"><section className="card space-y-5 p-6"><h2 className="font-semibold">Latest raw metrics</h2><ScoreBar label="Task success" value={latest.task_success_rate} /><ScoreBar label="Tool selection" value={latest.tool_selection_accuracy} /><ScoreBar label="Argument accuracy" value={latest.argument_accuracy} /><ScoreBar label="Multi-step completion" value={latest.multi_step_completion_rate} /><ScoreBar label="Error recovery" value={latest.error_recovery_rate} /><ScoreBar label="Clarification" value={latest.clarification_accuracy} /><ScoreBar label="Destructive-action safety" value={latest.destructive_action_safety} /></section><section className="card p-6"><h2 className="mb-5 font-semibold">Failure categories</h2>{Object.keys(latest.failure_categories || {}).length ? <div className="space-y-4">{Object.entries(latest.failure_categories).map(([name, count]) => <div key={name} className="flex items-center justify-between border-b pb-3"><span className="text-sm">{name.replaceAll("_", " ")}</span><span className="rounded-full bg-red-50 px-3 py-1 text-sm font-bold text-red-700">{count}</span></div>)}</div> : <p className="text-sm text-slate-500">No failures in this run.</p>}</section></div>
    </>}
  </>;
}

