"use client";

import {FormEvent, useEffect, useState} from "react";
import {useParams} from "next/navigation";
import {PageTitle, ProjectNav} from "@/components/ui";
import {getJSON, sendJSON, type Task} from "@/lib/api";

const emptyTask: Task = {id: "", project_id: "", version: 0, title: "", natural_language_instruction: "", difficulty: 1, category: "single_tool", required_tools: [], forbidden_tools: [], initial_state: {}, expected_final_state: [], expected_invariants: [], requires_clarification: false, safety_level: "normal", generated_or_manual: "manual", enabled: true};

export default function TasksPage() {
  const id = useParams<{id: string}>().id; const [tasks, setTasks] = useState<Task[]>([]); const [editing, setEditing] = useState<Task | null>(null); const [busy, setBusy] = useState(false);
  const load = () => getJSON<Task[]>(`/api/projects/${id}/tasks`).then(setTasks);
  useEffect(() => {getJSON<Task[]>(`/api/projects/${id}/tasks`).then(setTasks);}, [id]);
  async function generate() {setBusy(true); await sendJSON<Task[]>(`/api/projects/${id}/tasks/generate`, "POST"); await load(); setBusy(false);}
  async function save(task: Task, patch: Partial<Task>) {const payload = {...task, ...patch}; await sendJSON<Task>(`/api/tasks/${task.id}`, "PUT", payload); await load();}
  async function remove(task: Task) {if (!confirm(`Delete “${task.title}”?`)) return; await sendJSON(`/api/tasks/${task.id}`, "DELETE"); await load();}
  async function submit(event: FormEvent<HTMLFormElement>) {event.preventDefault(); const form = new FormData(event.currentTarget); const base = editing || emptyTask; const payload = {...base, title: form.get("title"), natural_language_instruction: form.get("instruction"), difficulty: Number(form.get("difficulty")), category: form.get("category")}; if (editing?.id) await sendJSON(`/api/tasks/${editing.id}`, "PUT", payload); else await sendJSON(`/api/projects/${id}/tasks`, "POST", payload); setEditing(null); await load();}
  return <><ProjectNav id={id} /><PageTitle eyebrow="Deterministic benchmark" title="Task suite" description={`${tasks.filter(x => x.enabled).length} of ${tasks.length} tasks enabled across seven difficulty levels.`} action={<div className="flex gap-2"><button onClick={() => setEditing(emptyTask)} className="btn-secondary">Add task</button><button onClick={generate} disabled={busy} className="btn-primary">{busy ? "Generating…" : "Generate tasks"}</button></div>} />
    {editing && <form onSubmit={submit} className="card mb-6 grid gap-4 p-6 md:grid-cols-4"><div><label className="label">Title</label><input name="title" className="input" defaultValue={editing.title} required /></div><div className="md:col-span-3"><label className="label">Natural-language instruction</label><input name="instruction" className="input" defaultValue={editing.natural_language_instruction} required /></div><div><label className="label">Difficulty</label><select name="difficulty" className="input" defaultValue={editing.difficulty}>{[1,2,3,4,5,6,7].map(level => <option key={level}>{level}</option>)}</select></div><div><label className="label">Category</label><input name="category" className="input" defaultValue={editing.category} /></div><div className="flex items-end gap-2 md:col-span-2"><button className="btn-primary">Save task</button><button type="button" onClick={() => setEditing(null)} className="btn-secondary">Cancel</button></div></form>}
    <section className="card overflow-hidden"><div className="grid grid-cols-[auto_1fr_100px_130px_130px] gap-4 border-b bg-slate-50 px-5 py-3 text-xs font-semibold uppercase tracking-wider text-slate-500"><span>On</span><span>Task</span><span>Level</span><span>Category</span><span>Actions</span></div><div className="divide-y">{tasks.map(task => <div key={task.id} className={`grid grid-cols-[auto_1fr_100px_130px_130px] items-center gap-4 px-5 py-4 ${task.enabled ? "" : "opacity-50"}`}><input aria-label={`Enable ${task.title}`} type="checkbox" checked={task.enabled} onChange={() => save(task, {enabled: !task.enabled})} /><div><p className="font-medium">{task.title}</p><p className="mt-1 line-clamp-1 text-sm text-slate-500">{task.natural_language_instruction}</p><div className="mt-2 flex gap-1">{task.required_tools.slice(0, 3).map(tool => <span key={tool} className="rounded bg-indigo-50 px-2 py-0.5 font-mono text-[10px] text-accent">{tool}</span>)}</div></div><span className="text-sm font-semibold">L{task.difficulty}</span><span className="text-xs text-slate-600">{task.category.replaceAll("_", " ")}</span><div className="flex gap-3 text-xs"><button onClick={() => setEditing(task)} className="text-accent">Edit</button><button onClick={() => remove(task)} className="text-red-600">Delete</button></div></div>)}</div></section>
  </>;
}
